version: '3.8'

services:
  short:
    build: .
    image: short
    command: script/start.sh
    volumes:
      - .:/app
      - short-gems:/gems
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      - THSL_DB_HOST=db
      - THSL_DB_USER=postgres

  db:
    image: postgres:10
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "password"

volumes:
  postgres-data:
  short-gems:
